### ISSUE TITLE
make install errors

### ISSUE THREAD

**Issue by alexriabtsev** [ActivityWatch/aw-watcher-spotify#11]
I'm trying to install this watcher but getting errors
`env PIP_USER=true make install
pip3 install --process-dependency-links  .

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --process-dependency-links
make: *** [install] Error 2`

Any chance to fix, @ErikBjare ?

**Comment by ErikBjare** [comment]
Fixing in https://github.com/ActivityWatch/aw-watcher-spotify/pull/12, should be merged momentarily.

**Comment by ErikBjare** [comment]
Note that it includes new installation instructions.
