### ISSUE TITLE
Running this in background on windows 11

### ISSUE THREAD

**Issue by sudokit** [ActivityWatch/aw-watcher-spotify#18]
How would i go about running this watcher in the background on boot on windows 11?

**Comment by maxfire2008** [comment]
You closed this issue. Did you solve the problem?

**Comment by sudokit** [comment]
Oh hello :p um can't exactly remember why I closed this haha its been some time. I think that it was just that i switched to linux pretty quickly. Task scheduling would be an option if you are trying the same thing.

**Comment by maxfire2008** [comment]
For anyone else who comes here in future: the most promising lead I got was to use [NSSM](https://nssm.cc/) to wrap it into a Windows service. But currently I'm just using aw-watcher-media-player.

@sudokit thanks for the advice.
