### ISSUE TITLE
While creating app redirect URI needs to be added for it to work

### ISSUE THREAD

**Issue by VirenMohindra** [ActivityWatch/aw-watcher-spotify#8]
`http://localhost/` needs to be added in the Redirect URIs section when creating the app from [developer.spotify.com](https://developer.spotify.com)

Otherwise you get a redirect error after adding the credentials.

This can hopefully be added to the docs so a potential new user doesn't need to go digging

**Comment by ErikBjare** [comment]
If you could send a PR adding this info to the README that'd be great!
